### ISSUE TITLE
why backup ssh config is removed ?

### ISSUE THREAD

**Issue by ihipop** [xwjdsh/manssh#7]
![image](https://user-images.githubusercontent.com/423077/41640593-e8b20bde-7494-11e8-9e81-c51209da751f.png)
should this be delete too?

**Comment by xwjdsh** [comment]
Sorry, I think this is a command that is not often used (use `cp` directly), so removed it in the latest release... README has not been updated.

If you think it should not be deleted, I'll restore it in the next release.

**Comment by ihipop** [comment]
It’s ok for what you've did, so,this `Feature` in `readme.md` should be deleted too

![](https://user-images.githubusercontent.com/423077/41640593-e8b20bde-7494-11e8-9e81-c51209da751f.png)

**Comment by xwjdsh** [comment]
I'll restore the command and release tonight or tomorrow night, thanks. :)

**Comment by ihipop** [comment]
老兄，我的意思说，拿掉也可以 随便你，但是Readme里面的Feature说明最好也更新一下...

**Comment by xwjdsh** [comment]
哈哈，我想了一下，觉得还是保持一致，不删它好一些。
